module.exports = {
  collections: ["id", "household_id", "ward_id", "user_id", "ts", "service_date", "wet_kg", "dry_kg", "hazard_kg", "segregated", "status", "lat", "lng", "photo", "notes"],
  payments: ["id", "household_id", "ward_id", "user_id", "amount", "period", "mode", "receipt_no", "ts", "lat", "lng", "notes"],
  grievances: ["id", "household_id", "ward_id", "block_id", "category", "description", "status", "priority", "raised_by", "raised_by_name", "ts", "lat", "lng", "photo", "assigned_to", "resolution", "resolved_ts"],
  assets: ["id", "asset_type", "name", "ward_id", "block_id", "condition", "capacity", "ownership", "lat", "lng", "photo", "notes", "surveyed_by", "ts", "toilet_count", "reason", "installed_on"],
  attendance: ["id", "user_id", "ward_id", "service_date", "in_ts", "out_ts", "lat", "lng"],
  households: ["id", "code", "head_name", "phone", "ward_id", "house_no", "category", "fee_slab", "family_size", "lat", "lng", "toilet", "soak_pit", "compost_pit", "active", "created_by", "updated_at"],
  gp_profiles: ["id", "ward_id", "sarpanch_name", "sarpanch_mobile", "secretary_name", "secretary_mobile", "updated_at"],
  villages: ["id", "ward_id", "name_hi", "name_en", "code", "fam_st", "fam_sc", "fam_obc", "fam_gen", "fam_total", "pop_st", "pop_sc", "pop_obc", "pop_gen", "pop_total", "updated_at"],
  schools: ["id", "ward_id", "village_id", "name", "kind", "toilets_total", "toilets_functional", "toilets_non_functional", "lat", "lng", "photo", "notes", "updated_at"],
  anganwadis: ["id", "ward_id", "village_id", "name", "toilets_total", "toilets_functional", "toilets_non_functional", "lat", "lng", "photo", "notes", "updated_at"],
  buildings: ["id", "ward_id", "village_id", "kind", "name", "toilets_total", "toilets_functional", "toilets_non_functional", "lat", "lng", "photo", "notes", "updated_at"],
  ihhl: ["id", "household_id", "ward_id", "status", "lat", "lng", "photo", "incentive_amount", "incentive_status", "incentive_date", "notes", "updated_by", "updated_at"],
  hotspots: ["id", "ward_id", "name", "lat", "lng", "photo", "cleanliness_status", "workflow", "notes", "raised_by", "ts", "updated_at"],
  cleanliness_cases: ["id", "ward_id", "hotspot_id", "school_id", "anganwadi_id", "location_name", "lat", "lng", "garbage_qty_kg", "before_photo", "after_photo", "uploaded_by", "status", "ts", "updated_at"],
  monitoring_visits: ["id", "ward_id", "target_type", "target_id", "activity", "observation", "status", "photo", "lat", "lng", "user_id", "ts"],
  greywater_cases: ["id", "ward_id", "accumulates", "location_name", "problem", "proposed_action", "action_status", "janpad_submitted_on", "soak_pit_asset_id", "lat", "lng", "photo", "raised_by", "ts", "updated_at"],
  swm_gp: ["id", "ward_id", "shed_available", "shed_usage", "dtd_happening", "dtd_reason", "dtd_frequency", "dtd_days_per_week", "segregation_happens", "segregation_reason", "segregation_location", "kit_available", "kit_status", "updated_at"],
  waste_sales: ["id", "ward_id", "waste_type", "qty_kg", "sale_date", "buyer", "notes", "created_by", "created_at"],
  pwmu_shipments: ["id", "ward_id", "qty", "unit", "ship_date", "destination", "notes", "created_by", "created_at"],
  honorarium: ["id", "ward_id", "paid", "reason", "amount_per_person", "people", "months", "total", "period", "notes", "updated_at"],
  waste_category_totals: ["id", "ward_id", "period", "plastic_kg", "metal_kg", "glass_kg", "mixed_kg", "updated_at"],
};
